### ISSUE TITLE
builder.send_project_to_api() ne fonctionne pas si on a utilisé builder.save_as_json() avant

### ISSUE THREAD

**Issue by RubenGres** [ign-gpao/builder-python#10]
#### Etapes pour reproduire

1. Créer un builder GPAO avec un ou plusieurs projects
2. Faire appel à la méthode save_as_json puis send_project_to_api du builder

#### Comportement Attendu

Un JSON est créé et les projets sont envoyés à l'API

#### Comportement Actuel

Un JSON est créé mais un erreur est renvoyé au moment de faire l'upload

### Configuration

Utilisation du coker-compose avec les versions suivantes:
gpao/database:0.9.0
gpao/api-gpao:1.14.0
gpao/monitor-gpao:1.30.0
gpao/client-gpao:0.13.2

### Autres Informations (log, message, etc...)

Impossible d'envoyer la requête API sur http://172.24.1.44:8080/api/project : ERROR =>  500 Server Error: Internal Server Error for url: http://172.24.1.44:8080/api/project

**Comment by leavauchier** [comment]
Je suis tombée sur le même problème. 
Il ne se produit que quand il y a des dépendances entre des `jobs` (les dépendances entre `projects` ont l'air ok par contre)

**Comment by leavauchier** [comment]
Après plus d'investigations : c'est le fait d'appliquer une 2e fois `Project.reorganize_job_dependencies(project)` qui pose problème : les dépendances ne sont plus détectées correctement, toutes les dépendances sont mises à -1.
